defmodule SeshLabWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :sesh_lab

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_sesh_lab_key",
    signing_salt: "+Ew7QwWI",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # User-uploaded product photos. Dev: priv/static/uploads. Prod: /data/uploads
  # via config/prod.exs. Must precede the "/" Plug.Static below so /uploads/*
  # bypasses :only on the priv/static plug.
  plug Plug.Static,
    at: "/uploads",
    from:
      Application.compile_env(
        :sesh_lab,
        :uploads_dir,
        {:sesh_lab, "priv/static/uploads"}
      ),
    gzip: false,
    only: ~w(products)

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :sesh_lab,
    gzip: not code_reloading?,
    only: SeshLabWeb.static_paths(),
    # `only_matching` is a PREFIX match; the digested filename is
    # `manifest-<hash>.webmanifest`, so we match on the `manifest` prefix to
    # cover both the dev (literal) and prod (digested) names.
    only_matching: ~w(manifest),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :sesh_lab
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug SeshLabWeb.Router
end
